### ISSUE TITLE
RssService Error

### ISSUE THREAD

**Issue by GerhardPue** [nerdability/AndroidRssReader#10]
I get this error ... solutions? 

E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.me, PID: 2032
    java.lang.NullPointerException
            at com.me.rss.RssService$1.run(RssService.java:52)
            at android.app.Activity.runOnUiThread(Activity.java:4713)
            at com.me.rss.RssService.onPostExecute(RssService.java:49)
            at com.me.rss.RssService.onPostExecute(RssService.java:27)
            at android.os.AsyncTask.finish(AsyncTask.java:632)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by rnascimento13** [comment]
im also with the same problem, imported to android studio and added dependency on gradle
no deal here

**Comment by MohNage7** [comment]
did you find solution for this problem ? if so , please help me bcuz i face the same problem right now :|

**Comment by pengjfcn** [comment]
me too

**Comment by rzfzr** [comment]
Solution on this?

**Comment by robhinds** [comment]
Having a quick look at the code, it looks like there must have been an error parsing the XML feed - the exceptions caught all have a very basic log statement which might give you some clue, but you might need to add more logging or step through with a debugger.

Basically - from that stack trace, the NullPointerException is coming from line 52 in RssService.java - which means the variable `articles` is null.  This variable is passed through and is the returned result from the method in that class `doInBackground` - you will see that the only scenario in which the `return null` happens is if the `try` block fails to get to the end.

It all needs better exception handling - but to get to the bottom of the error just check what error is being thrown in that method.

**Comment by bigsteve4288** [comment]
Hi Rob,

Can you please reach out, I'm having an issue returning the view on my galaxy s6? Have you ever had this issue?

10-31 22:09:21.433 11993-18040/com.nerdability.android E/ASYNC: PARSING FINISHED
10-31 22:09:21.434 11993-11993/com.nerdability.android E/ASYNC: POST EXECUTE
10-31 22:09:21.446 11993-11993/com.nerdability.android D/ViewRootImpl@cbbe6bb[ArticleListActivity]: mHardwareRenderer.destroy()#4
10-31 22:09:21.447 11993-11993/com.nerdability.android D/ViewRootImpl@cbbe6bb[ArticleListActivity]: dispatchDetachedFromWindow
10-31 22:09:21.462 11993-11993/com.nerdability.android D/InputTransport: Input channel destroyed: fd=73
10-31 22:09:21.466 11993-11993/com.nerdability.android D/ViewRootImpl@cb626e2[ArticleListActivity]: MSG_WINDOW_FOCUS_CHANGED 1
10-31 22:09:21.466 11993-11993/com.nerdability.android D/ViewRootImpl@cb626e2[ArticleListActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 489888785920}
10-31 22:09:21.470 11993-11993/com.nerdability.android E/ViewRootImpl: sendUserActionEvent() mView == null

**Comment by robhinds** [comment]
@bigsteve4288 do you have more of the logs or a stacktrace? I can't see any details of the error in that log.

**Comment by bigsteve4288** [comment]
![image](https://user-images.githubusercontent.com/4561636/32267038-d8a7549e-beb7-11e7-98e0-f0161794fefe.png)

**Comment by bigsteve4288** [comment]
The parser is not returning any articles from http://www.espn.com/espn/rss/news

So I'm thinking its something I'm doing wrong with the parser

**Comment by bigsteve4288** [comment]
I'm pasting a full log stack

**Comment by bigsteve4288** [comment]
11-01 03:36:37.408 14711-14711/? E/Zygote: v2
11-01 03:36:37.408 14711-14711/? I/libpersona: KNOX_SDCARD checking this for 10222
11-01 03:36:37.408 14711-14711/? I/libpersona: KNOX_SDCARD not a persona
11-01 03:36:37.408 14711-14711/? E/Zygote: accessInfo : 0
11-01 03:36:37.409 14711-14711/? W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.0_0005, [-1 -1 -1 -1 0 1]
11-01 03:36:37.410 14711-14711/? I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.nerdability.android 
11-01 03:36:37.413 14711-14711/? I/art: Late-enabling -Xcheck:jni
11-01 03:36:37.437 14711-14711/? D/TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
11-01 03:36:37.456 14711-14711/com.nerdability.android W/ActivityThread: Application com.nerdability.android is waiting for the debugger on port 8100...
11-01 03:36:37.456 14711-14711/com.nerdability.android I/System.out: Sending WAIT chunk
11-01 03:36:38.530 14711-14718/com.nerdability.android I/art: Debugger is active
11-01 03:36:38.657 14711-14711/com.nerdability.android I/System.out: Debugger has connected
11-01 03:36:38.657 14711-14711/com.nerdability.android I/System.out: waiting for debugger to settle...
11-01 03:36:38.857 14711-14711/com.nerdability.android I/System.out: waiting for debugger to settle...
11-01 03:36:39.058 14711-14711/com.nerdability.android I/System.out: waiting for debugger to settle...
11-01 03:36:39.258 14711-14711/com.nerdability.android I/System.out: waiting for debugger to settle...
11-01 03:36:39.458 14711-14711/com.nerdability.android I/System.out: waiting for debugger to settle...
11-01 03:36:39.658 14711-14711/com.nerdability.android I/System.out: waiting for debugger to settle...
11-01 03:36:39.859 14711-14711/com.nerdability.android I/System.out: waiting for debugger to settle...
11-01 03:36:40.059 14711-14711/com.nerdability.android I/System.out: waiting for debugger to settle...
11-01 03:36:40.259 14711-14711/com.nerdability.android I/System.out: debugger has settled (1394)
11-01 03:36:40.312 14711-14711/com.nerdability.android W/System: ClassLoader referenced unknown path: /data/app/com.nerdability.android-2/lib/arm64
11-01 03:36:40.329 14711-14711/com.nerdability.android I/InstantRun: starting instant run server: is main process
11-01 03:36:40.387 14711-14718/com.nerdability.android I/art: Starting a blocking GC Instrumentation
11-01 03:36:40.585 14711-14718/com.nerdability.android I/art: Starting a blocking GC Instrumentation
11-01 03:36:40.616 14711-14711/com.nerdability.android E/ASYNC: PRE EXECUTE
11-01 03:36:40.741 14711-14711/com.nerdability.android D/ViewRootImpl@19355f0[ArticleListActivity]: ThreadedRenderer.create() translucent=true
11-01 03:36:40.756 14711-14711/com.nerdability.android D/InputTransport: Input channel constructed: fd=71
11-01 03:36:40.757 14711-14711/com.nerdability.android D/ViewRootImpl@19355f0[ArticleListActivity]: setView = DecorView@cdcb5ee[ArticleListActivity] touchMode=true
11-01 03:36:40.771 14711-14786/com.nerdability.android D/NetworkSecurityConfig: No Network Security Config specified, using platform default
11-01 03:36:40.779 14711-14786/com.nerdability.android I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
11-01 03:36:40.780 14711-14786/com.nerdability.android I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
11-01 03:36:40.796 14711-14711/com.nerdability.android D/AbsListView: Get MotionRecognitionManager
11-01 03:36:40.798 14711-14711/com.nerdability.android D/MotionRecognitionManager: mSContextService = com.samsung.android.hardware.context.ISemContextService$Stub$Proxy@c7c6b2
11-01 03:36:40.800 14711-14711/com.nerdability.android D/MotionRecognitionManager: motionService = com.samsung.android.gesture.IMotionRecognitionService$Stub$Proxy@3679bfe
11-01 03:36:40.800 14711-14711/com.nerdability.android D/MotionRecognitionManager: motionService = com.samsung.android.gesture.IMotionRecognitionService$Stub$Proxy@3679bfe
11-01 03:36:40.832 14711-14711/com.nerdability.android D/ViewRootImpl@18be9d3[ArticleListActivity]: ThreadedRenderer.create() translucent=false
11-01 03:36:40.840 14711-14711/com.nerdability.android D/InputTransport: Input channel constructed: fd=73
11-01 03:36:40.842 14711-14711/com.nerdability.android D/ViewRootImpl@18be9d3[ArticleListActivity]: setView = DecorView@6030910[ArticleListActivity] touchMode=true
11-01 03:36:40.854 14711-14711/com.nerdability.android D/ViewRootImpl@19355f0[ArticleListActivity]: dispatchAttachedToWindow
11-01 03:36:40.910 14711-14711/com.nerdability.android D/ViewRootImpl@19355f0[ArticleListActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[28,865][1052,1117] result=0x27 surface={isValid=true 489888785920} surfaceGenerationChanged=true
11-01 03:36:40.912 14711-14711/com.nerdability.android D/ViewRootImpl@19355f0[ArticleListActivity]: mHardwareRenderer.initialize() mSurface={isValid=true 489888785920} hwInitialized=true
11-01 03:36:40.951 14711-14785/com.nerdability.android D/libEGL: loaded /vendor/lib64/egl/libGLES_mali.so
11-01 03:36:40.956 14711-14711/com.nerdability.android D/ViewRootImpl@18be9d3[ArticleListActivity]: dispatchAttachedToWindow
11-01 03:36:40.990 14711-14785/com.nerdability.android I/OpenGLRenderer: Initialized EGL, version 1.4
11-01 03:36:40.990 14711-14785/com.nerdability.android D/OpenGLRenderer: Swap behavior 1
11-01 03:36:40.997 14711-14785/com.nerdability.android D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1024x252]-format:1
11-01 03:36:41.023 14711-14711/com.nerdability.android D/ViewRootImpl@18be9d3[ArticleListActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1080,1920] result=0x7 surface={isValid=true 489596849664} surfaceGenerationChanged=true
11-01 03:36:41.025 14711-14785/com.nerdability.android D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
11-01 03:36:41.026 14711-14711/com.nerdability.android D/ViewRootImpl@18be9d3[ArticleListActivity]: mHardwareRenderer.initialize() mSurface={isValid=true 489596849664} hwInitialized=true
11-01 03:36:41.049 14711-14711/com.nerdability.android D/ViewRootImpl@19355f0[ArticleListActivity]: MSG_WINDOW_FOCUS_CHANGED 1
11-01 03:36:41.050 14711-14711/com.nerdability.android D/ViewRootImpl@19355f0[ArticleListActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 489888785920}
11-01 03:36:41.077 14711-14786/com.nerdability.android E/ASYNC: PARSING FINISHED
11-01 03:36:41.130 14711-14711/com.nerdability.android D/ViewRootImpl@19355f0[ArticleListActivity]: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
11-01 03:36:41.212 14711-14711/com.nerdability.android D/ViewRootImpl@18be9d3[ArticleListActivity]: MSG_RESIZED_REPORT: ci=Rect(0, 63 - 0, 0) vi=Rect(0, 63 - 0, 0) or=1
11-01 03:36:42.410 14711-14716/com.nerdability.android I/art: Do partial code cache collection, code=2656B, data=29KB
11-01 03:36:42.411 14711-14716/com.nerdability.android I/art: After code cache collection, code=0B, data=29KB
11-01 03:36:42.411 14711-14716/com.nerdability.android I/art: Increasing code cache capacity to 128KB
11-01 03:52:02.865 14711-14711/com.nerdability.android E/ASYNC: POST EXECUTE
11-01 03:52:02.968 14711-14711/com.nerdability.android D/ViewRootImpl@19355f0[ArticleListActivity]: mHardwareRenderer.destroy()#4
11-01 03:52:02.968 14711-14711/com.nerdability.android D/ViewRootImpl@19355f0[ArticleListActivity]: dispatchDetachedFromWindow
11-01 03:52:02.990 14711-14711/com.nerdability.android D/InputTransport: Input channel destroyed: fd=71
11-01 03:52:02.995 14711-14711/com.nerdability.android I/Choreographer: Skipped 52 frames!  The application may be doing too much work on its main thread.
11-01 03:52:03.024 14711-14711/com.nerdability.android D/ViewRootImpl@18be9d3[ArticleListActivity]: Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x1 surface={isValid=true 489596849664} surfaceGenerationChanged=false
11-01 03:52:03.028 14711-14711/com.nerdability.android D/AbsListView:  onsize change 
11-01 03:52:03.048 14711-14711/com.nerdability.android D/ViewRootImpl@18be9d3[ArticleListActivity]: MSG_WINDOW_FOCUS_CHANGED 1
11-01 03:52:03.050 14711-14711/com.nerdability.android D/ViewRootImpl@18be9d3[ArticleListActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 489596849664}
11-01 03:52:03.061 14711-14711/com.nerdability.android V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@7a0c1e7 nm : com.nerdability.android ic=null
11-01 03:52:03.061 14711-14711/com.nerdability.android I/InputMethodManager: [IMM] startInputInner - mService.startInputOrWindowGainedFocus
11-01 03:52:03.068 14711-14711/com.nerdability.android E/ViewRootImpl: sendUserActionEvent() mView == null
11-01 03:52:03.072 14711-28459/com.nerdability.android D/InputTransport: Input channel constructed: fd=71
11-01 03:52:03.087 14711-14711/com.nerdability.android V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@a312194 nm : com.nerdability.android ic=null
