### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Houweida** [nerdability/AndroidRssReader#2]
i receive a lang.nullPointerException :(

**Comment by avade** [comment]
Please provide some more information (copy of the stack trace etc)...

**Comment by netwrkx** [comment]
i have the same problem, here is my logcat

09-11 00:34:56.841: I/Choreographer(972): Skipped 284 frames!  The application may be doing too much work on its main thread.
09-11 00:34:56.922: E/ASYNC(972): POST EXECUTE
09-11 00:34:56.941: D/AndroidRuntime(972): Shutting down VM
09-11 00:34:56.951: W/dalvikvm(972): threadid=1: thread exiting with uncaught exception (group=0x40a71930)
09-11 00:34:56.983: E/AndroidRuntime(972): FATAL EXCEPTION: main
09-11 00:34:56.983: E/AndroidRuntime(972): java.lang.NullPointerException
09-11 00:34:56.983: E/AndroidRuntime(972):  at com.nerdability.android.rss.RssService$1.run(RssService.java:52)
09-11 00:34:56.983: E/AndroidRuntime(972):  at android.app.Activity.runOnUiThread(Activity.java:4644)
09-11 00:34:56.983: E/AndroidRuntime(972):  at com.nerdability.android.rss.RssService.onPostExecute(RssService.java:49)
09-11 00:34:56.983: E/AndroidRuntime(972):  at com.nerdability.android.rss.RssService.onPostExecute(RssService.java:1)
09-11 00:34:56.983: E/AndroidRuntime(972):  at android.os.AsyncTask.finish(AsyncTask.java:631)
09-11 00:34:56.983: E/AndroidRuntime(972):  at android.os.AsyncTask.access$600(AsyncTask.java:177)
09-11 00:34:56.983: E/AndroidRuntime(972):  at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
09-11 00:34:56.983: E/AndroidRuntime(972):  at android.os.Handler.dispatchMessage(Handler.java:99)
09-11 00:34:56.983: E/AndroidRuntime(972):  at android.os.Looper.loop(Looper.java:137)
09-11 00:34:56.983: E/AndroidRuntime(972):  at android.app.ActivityThread.main(ActivityThread.java:5041)
09-11 00:34:56.983: E/AndroidRuntime(972):  at java.lang.reflect.Method.invokeNative(Native Method)
09-11 00:34:56.983: E/AndroidRuntime(972):  at java.lang.reflect.Method.invoke(Method.java:511)
09-11 00:34:56.983: E/AndroidRuntime(972):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
09-11 00:34:56.983: E/AndroidRuntime(972):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
09-11 00:34:56.983: E/AndroidRuntime(972):  at dalvik.system.NativeStart.main(Native Method)

**Comment by gandhar** [comment]
i get the same error, on android 4.3.

**Comment by CoolSLind** [comment]
ARTICLES_LIMIT in the RssHandler Class seems to be set to 15, while the feed contains 50+ articles. This generates a SAXException which returns null instead of the article list from the parsing. A fix would be to set ARTICLES_LIMIT higher than the number of articles in the rss-feed or return the article list if a SAXException is called in the RssService class. Preferably a subclass to SAXException to be sure that it is a wanted exception.

**Comment by sebastianroming** [comment]
Any solution for this? I get the same error. (increase of RssHandler.ARTICLES_LIMIT does not work).

Update:
I could determine that the Encoding of the Feed is the problem. If the XML declaration is "ISO-8859-1", but the file itself is encoded as UTF-8, you get the same error. Will investigate.

**Comment by ghost** [comment]
Anything new with this issue? I have the same problem at the moment.

Cheers

**Comment by ghost** [comment]
I chaged article_limits from 15 to 999 and it works!

**Comment by tekwe** [comment]
I changed article_limits to 999 but the app still shut down. Any other suggestion?
