### ISSUE TITLE
ArticleListActivity error

### ISSUE THREAD

**Issue by ghost** [nerdability/AndroidRssReader#6]
Hello,
after i solved the previous error, it was a bad for me i just had to add appcompt..

now i'm able to run the application, but i get the following error and the application shuts down, here what it gave me:

<code>
04-12 14:47:23.509: E/AndroidRuntime(1049): FATAL EXCEPTION: main
04-12 14:47:23.509: E/AndroidRuntime(1049): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.nerdability.android/com.nerdability.android.ArticleListActivity}: java.lang.ClassNotFoundException: com.nerdability.android.ArticleListActivity
04-12 14:47:23.509: E/AndroidRuntime(1049):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1880)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at android.app.ActivityThread.access$600(ActivityThread.java:123)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at android.os.Handler.dispatchMessage(Handler.java:99)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at android.os.Looper.loop(Looper.java:137)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at android.app.ActivityThread.main(ActivityThread.java:4424)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at java.lang.reflect.Method.invokeNative(Native Method)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at java.lang.reflect.Method.invoke(Method.java:511)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at dalvik.system.NativeStart.main(Native Method)
04-12 14:47:23.509: E/AndroidRuntime(1049): Caused by: java.lang.ClassNotFoundException: com.nerdability.android.ArticleListActivity
04-12 14:47:23.509: E/AndroidRuntime(1049):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at android.app.Instrumentation.newActivity(Instrumentation.java:1023)
04-12 14:47:23.509: E/AndroidRuntime(1049):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1871)
04-12 14:47:23.509: E/AndroidRuntime(1049):     ... 11 more
04-12 14:47:23.661: I/dalvikvm(1049): threadid=3: reacting to signal 3
04-12 14:47:23.674: I/dalvikvm(1049): Wrote stack traces to '/data/anr/traces.txt'
04-12 14:47:24.061: I/dalvikvm(1049): threadid=3: reacting to signal 3
04-12 14:47:24.073: I/dalvikvm(1049): Wrote stack traces to '/data/anr/traces.txt'
</code>

it gives me error in RssService, but i don't know whats the problem in it! i done nothing to the source code except adding the appcompt-v4 jar file!!
can you please help me?

**Comment by redapple1900** [comment]
ARE you using the the package or another one ?
