### ISSUE TITLE
Unable to instantiate activity component info

### ISSUE THREAD

**Issue by viperflux** [nerdability/AndroidRssReader#8]
Hey guys!, can you please help me with this error? i was unable to solve it and i tried and searched a lot!

<pre><code>
06-09 15:53:14.722: E/AndroidRuntime(3493): FATAL EXCEPTION: main
06-09 15:53:14.722: E/AndroidRuntime(3493): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.nerdability.android/com.nerdability.android.ArticleListActivity}: java.lang.ClassNotFoundException: com.nerdability.android.ArticleListActivity
06-09 15:53:14.722: E/AndroidRuntime(3493):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1993)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2104)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at android.app.ActivityThread.access$600(ActivityThread.java:132)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1157)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at android.os.Handler.dispatchMessage(Handler.java:99)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at android.os.Looper.loop(Looper.java:137)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at android.app.ActivityThread.main(ActivityThread.java:4575)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at java.lang.reflect.Method.invokeNative(Native Method)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at java.lang.reflect.Method.invoke(Method.java:511)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at dalvik.system.NativeStart.main(Native Method)
06-09 15:53:14.722: E/AndroidRuntime(3493): Caused by: java.lang.ClassNotFoundException: com.nerdability.android.ArticleListActivity
06-09 15:53:14.722: E/AndroidRuntime(3493):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at android.app.Instrumentation.newActivity(Instrumentation.java:1023)
06-09 15:53:14.722: E/AndroidRuntime(3493):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1984)
06-09 15:53:14.722: E/AndroidRuntime(3493):     ... 11 more
</code></pre>

**Comment by viperflux** [comment]
can anybody help me please?

**Comment by edholland** [comment]
This seems to be related to not exporting the android support v4 lib with the package

**Comment by viperflux** [comment]
so what I've to do?

**Comment by edholland** [comment]
put the jar into your project, ensure that its in your classpath and check thats its being exported when you build the package
